### PR TITLE
Added Windows build instructions

### PR DESCRIPTION
**Pull request by sgraf812**

### CODE REVIEW

**Review by jxv — APPROVED** [review]
I don't know anything about building with stack on Windows. But I'm surprised to see `pacman`! I'll merge it.

**Comment by sgraf812** [comment]
Thanks for the quick the merge! Too quick, in fact, I forgot to add `mingw-w64-x86_64-pkg-config` to the list. Also it seems that because of https://github.com/haskell-game/sdl2/issues/139 we need to depend on sdl2-2.3.0.1 (stack.yaml). Could you add that by hand or should I open another PR?

**Comment by jxv** [comment]
@sgraf812  added. Double check?

**Comment by sgraf812** [comment]
Yes, that works! Although it doesn't, because of https://github.com/haskell-game/sdl2/issues/139 which was fixed in `sdl2-2.3.0.1` (lts-9 is stuck on 2.2.0). And even then, similar fixes would need to be made to `sdl2-image` (https://github.com/sbidin/sdl2-image/pull/6).

I'm currently on a local version I changed the stack.yaml file to point to fixed versions of the package, but even then dino-rush starts and exits with 127 immediately. I'll investigate why.

**Comment by sgraf812** [comment]
Just for the record, I can get the examples from the `sdl2` repo to work, but when I try to start any lesson from https://github.com/palf/haskell-sdl2-examples, which also uses a supposedly fixed `sdl2-image`, it exits immediately without ever creating a window.

**Comment by jmn** [comment]
I can't get this to build on windows following the given instructions. I get the error (referenced above)
`C:/Users/jmn/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/include/SDL2/SDL_main.h:111:17: error: conflicting types for 'SDL_main'`

**Comment by sgraf812** [comment]
@jmn see the referenced issues in https://github.com/jxv/dino-rush/pull/1#issuecomment-369851405. Things compile with the fixes, but running the executable immediately exits with 127. That's not specific to `dino-rush`, however.

**Pull request merged**
